### ISSUE TITLE
Still calling 1.7.10 CoFH API in 1.9.4

### ISSUE THREAD

**Issue by Dragnier** [MrDimkasStudio/MachinePowerCraft-api#1]
Here is a link to the closed issue at Refined Storage because I thought it was their mod due to the problem going away if I removed it. However, they have stated that it is apparently your mod causing the problem.

https://github.com/raoulvdberge/refinedstorage/issues/114#issuecomment-226279550

 Raoul <notifications@github.com>
To raoulvdberge/refinedstorage
CC Dragnier Author
Today at 2:36 PM

Ah

* CoFHAPI (1.7.10R1.0.2) from [1.9.4] MachinePowerCraft-1.1.2.jar

MachinePowerCraft is using the CoFH 1.7.10 API...

—

**Comment by MrDimkasStudio** [comment]
Thanks for letting me know that! I will download RefinedStorage's RF API, so no issue will happen Wait till 1.1.4 =)
