### ISSUE TITLE
Quarry Problems  1.10.2

### ISSUE THREAD

**Issue by Stuart74** [MrDimkasStudio/MachinePowerCraft-api#2]
I am the modpack owner  and  i recieved an issue relating to your quarry.

In short it mines the solar panels irrespective where they are located as it mined the solar panels when they were outside the selected area and then were duplicated when it was placed in the quarrys output chest. The speed of the Quarry also crashes the client (not the server at this time) and it also crashed the game with a slow quarry once it had duplicated the solar panels.
 
Machine Power Craft Version MachinePowerCraft - 1.10.2_1.1.8
Forge Version 12.18.1.2014
 
Unfortunatly i was given no crash reports to attach to this issue

**Comment by Stuart74** [comment]
Is this mod still being supported?

**Comment by MrDimkasStudio** [comment]
Yes, it is, BUT I'm sick at the moment!

**Comment by Stuart74** [comment]
Ah ok glad to see somebodys alive may not be well but alive Hope you get better soon bud no great rush

**Comment by MrDimkasStudio** [comment]
In the MPC2 I reduced quarry's speed
