### ISSUE TITLE
Crash Caused by IC2 API not implemented correctly Possibly

### ISSUE THREAD

**Issue by Stuart74** [MrDimkasStudio/MachinePowerCraft-api#3]
Seems that when i have machine power crafted enabled with IC2 installed the client will crash due to an API issue on Machine Power Craft side.  I disable Machine Power Craft the pack loads just fine. 

This issue was raised in the IC2 Forums here [IC2 Forum Post](http://forum.industrial-craft.net/index.php?page=Thread&postID=202113)

Crash Report [Gist](https://gist.github.com/Stuart74/9a9248e9ea736abfc192e818f5041a5c)

Unsure if its due to your code not being right for the IC2 API or if its IC2 fault but it does refer to your mod at the bottom of the report 

Reference to API: [gist](https://gist.github.com/Stuart74/a3a58a50d79926f6ca93239f8160a33d)

IC2 Version: IC2 1.10/2.2.6.15-ex110 
MachinePowerCraft Version 1.10.2-1.1.8

**Comment by Stuart74** [comment]
Have removed your mod from the pack as now it is clashing with ender io's API and i simply can't keep this mod in the pack if its this unstable 

crash report [Crash Report](https://gist.github.com/Stuart74/43256a52a70057cf5723bb904cee8109)

**Comment by MrDimkasStudio** [comment]
MPC2 removes IC2 api

**Comment by Stuart74** [comment]
if your mod is removing API's then i can see it not being used as it stands then its now removing EnderIO's API also so making it unusable in any server that either has Ender IO or IC2 cant see this being a good thing

**Comment by MrDimkasStudio** [comment]
I meant that I removed it from my source code

**Comment by Stuart74** [comment]
Ah ok sweet does this include EnderIO as well as IC2

**Comment by Stuart74** [comment]
thought i say thanks works like a charm now
