### ISSUE TITLE
API Issues 

### ISSUE THREAD

**Issue by Stuart74** [MrDimkasStudio/MachinePowerCraft-api#4]
Linking to AbyssalCraft Issue due to it crashing with further API Errors when i Updated AbyssalCraft and it now runs on forge 2046 

https://github.com/Shinoow/AbyssalCraft/issues/129

**Comment by MrDimkasStudio** [comment]
Why did you open this issue?

**Comment by Stuart74** [comment]
Seems i cant update Abyssalcraft due to your mod and its API issues with using forge 2046 Everything seems find for my current version of forge but if i wish to update any mod past the current version of forge 2014 i get your API Errors continually. 

Since your mod is the only mod currently that generates Lead And Silver apart from IC2 I need it in the pack but it dislikes when a forge version is needed to be updated.

https://gist.github.com/Stuart74/519f6ada9421b5a760802caf16640a29
